### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by valandexx** [Quatrecentquatre-404/discord-badges-finder#1]
If you make this in Python, it'll be very useful. Thank you.

**Comment by Quatrecentquatre-404** [comment]
I'm goiing to think about that and I may release it soon.

**Comment by valandexx** [comment]
did u finish thinking @Quatrecentquatre-404

**Comment by Quatrecentquatre-404** [comment]
Yeah, I think I'm gonna give a shot to the idea.
